name: Flutter Integration Tests

# Controlamos cuándo se dispara el pipeline (Triggers)
on:
  - push

jobs:
  integration-tests:
    runs-on: self-hosted

    env:
      NODE_TLS_REJECT_UNAUTHORIZED: '0'

    steps:
      - name: Git Clone Repository
        uses: actions/checkout@v4

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Flutter Test 
        run:  flutter test

      - name: Create directorio para reporte
        run: mkdir -p integration_test/utils/report
        
      - name: Run Integration Tests
        run: flutter test integration_test/autenticacion/autentication_integration_test.dart -d RFXNW19926009314 --machine -r json > lib/src/report/test-results.json

      - name: Generate Report
        run: dart run lib/src/report/generate_report.dart

      - name: Upload Test Results
        if: always() # Se ejecuta aunque las pruebas fallen
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-report
          path: lib/src/report/report.html

      - name: Publish Report Summary
        if: always()
        run: |
          echo "### 📊 Resultado de Pruebas de Integración" >> $GITHUB_STEP_SUMMARY
          echo "La ejecución de las pruebas ha finalizado." >> $GITHUB_STEP_SUMMARY
          echo "- **Reporte generado:** [Descargar desde Artifacts](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> $GITHUB_STEP_SUMMARY
          echo "- **Ruta del reporte:** \`lib/src/report/report.html\`" >> $GITHUB_STEP_SUMMARY
          if [ -f "lib/src/report/report.html" ]; then
            echo "✅ El archivo de reporte HTML se encuentra disponible como recurso." >> $GITHUB_STEP_SUMMARY
          else
            echo "⚠️ No se encontró el archivo HTML para visualizar." >> $GITHUB_STEP_SUMMARY
          fi
