name: Flutter Integration Tests

# Controlamos cuándo se dispara el pipeline (Triggers)
on:
  - push

jobs:
  integration-tests:
    runs-on: self-hosted

    steps:
      - name: Git Clone Repository
        uses: actions/checkout@v4

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Flutter Test 
        run:  flutter test

      - name: Run Integration Tests
        run: |
          # Aseguramos que el directorio de reportes exista
          mkdir -p integration_test/utils/report
          
          # Ejecución del comando (Nota: se asume que el dispositivo está conectado al runner)
          flutter test integration_test/autenticacion/autentication_integration_test.dart --machine -r json > lib/src/report/test-results.json -d RFXNW19926009314
